### ISSUE TITLE
How to differentiate multiple rooms in a multiplayer game? Do we need to open a separate port for each room?

### ISSUE THREAD

**Issue by Magic-KK** [grazianobolla/godot4-multiplayer-template#1]

**Comment by Magic-KK** [comment]
> There is no concept of "room", only servers. So yeah you would need 1 server per "match" or "room". Maybe you can modify the code to have a single server and separate the players into different places but that would require some work.
> 
> Are you using Linux or Windows?
 I'm using Windows.

**Comment by grazianobolla** [comment]
Have you experienced any stutter or jitter? I've always used Linux and recently I decided to test the project in Windows and it was not working properly.

**Comment by Magic-KK** [comment]
> 



> Have you experienced any stutter or jitter? I've always used Linux and recently I decided to test the project in Windows and it was not working properly.

I previously experienced occasional shaking issues with your program on Windows.

**Comment by Magic-KK** [comment]
I have tested your FPS project and it seems to work well. I am in China and my friend is in Japan, with the server being launched in Japan.

**Comment by grazianobolla** [comment]
Yeah, It seems to only happen locally IDK why, thanks for your feedback.
